###
post http://localhost:3000/courses
Content-Type: application/json

{
    "title": "New Course 2",
   "description": "Description for New Course 2"
}

###
get http://localhost:3000/courses

### Eliminar
delete http://localhost:3000/courses/2

### Actualizar
put http://localhost:3000/courses/3
Content-Type: application/json

{
   "title": "Updated Course",
}